export default {
  SIGNIN: "SIGNIN",
  SIGNOUT: "SIGNOUT",
  ALERT_GLOBAL: "ALERT_GLOBAL",
  DISABLE_ALERT_GLOBAL: "DISABLE_ALERT_GLOBAL",
  SET_GLOBAL_CAUSES:"SET_GLOBAL_CAUSES",
  SET_GLOBAL_PROJECTS:"SET_GLOBAL_PROJECTS"
};
